### PR TITLE
floaty ball example should use frame management

### PR DESCRIPTION
**Pull request by joshgoebel**

### CODE REVIEW

**Comment by joshgoebel** [comment]
This also depends on buttonsState() being merged.

**Comment by shogerr** [comment]
See issue #70, but I will merge this change and then we can address removing it for 1.0, and then putting the codebase in place where it can be reworked without being a priority for this repo.

**Comment by joshgoebel** [comment]
Well does Arduboy itself want to host games that people can fork or do we want it gone gone and someone else responsibility completely?  I can understand why not every game would go into examples.

**Comment by shogerr** [comment]
I would personally like to see it forked into another repository that Arduboy maintains in the end.

**Pull request merged**
