### PR TITLE
@PlatformIO Library Registry manifest file

### PR DESCRIPTION
**Pull request by valeros**
Description
- This library in Web Registry: http://platformio.org/lib/show/192/Arduboy
- Library Manager: http://docs.platformio.org/en/latest/librarymanager/index.html
- Specification: [library.json](http://docs.platformio.org/en/latest/librarymanager/config.html)

### CODE REVIEW

**Comment by MLXXXp** [comment]
Does this have to be in the root directory of the Arduboy library? Does it get copied somewhere else for use? Could it go under the _extras_ folder, such as _extras/PlatformIO/library.json_?

**Comment by ivankravets** [comment]
@MLXXXp  `library.json` is a library manifest and should be located in the root of repo like `library.properties` (which you have). In PlatformIO 3.0 developers be able to install (or depend on it) your library (if it contains `library.json`) directly from VCS.

Thanks.

**Comment by MLXXXp** [comment]
> - This library in Web Registry: http://platformio.org/lib/show/192/Arduboy

You shouldn't be using https://github.com/Arduboy/Arduboy.git
for registering the Arduboy library. The _master_ branch of Arduboy library repository is used for development for the next release. It may be unstable and have changes that make it incompatible with the latest stable released version of the library.

Only [released versions of the Arduboy library](https://github.com/Arduboy/Arduboy/releases) should be used by the general public for developing sketches (actually, only the _latest_ released version).

The latest released version of the library should be found as the _stable_ branch in the repository:
https://github.com/Arduboy/Arduboy/tree/stable

**Comment by ivankravets** [comment]
@valeros please change from `"version": "1.2.0-alpha"` to `"version": "1.1"`

**Comment by ivankravets** [comment]
@MLXXXp if `version` field is specified, PlatformIO Library Crawler will try to find release branch automatically. More details http://docs.platformio.org/en/latest/librarymanager/config.html#version

**Comment by shogerr** [comment]
I'm actually not against this. The library is tied into some npm tools as we go along and the `package.json` will let us define some dependencies etc.

**Comment by ivankravets** [comment]
@rogosher sorry, I don't understand you. How does `library.json` relate to `package.json`? `libary.json` is the manifest for C/C++ libraries, not for JavaScript.

**Comment by MLXXXp** [comment]
My only issue with including this file, and the reason I was wondering if it could go in a _PlatformIO_ folder under extras, is that people looking at the repository may wonder _"What the heck is this file for?"_

It isn't part of the [library specification](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification) and nothing in the file itself indicates that it's for PlatformIO (and you can't put comments in a _.json_ file). So, we should document its purpose somewhere else in the repository. Maybe we can add a _library.json.md_ file describing the purpose of _library.json_ and how it should be maintained.

Also keep in mind that for those responsible for maintaining the repository it will be another file that they have to remember to keep up to date. It's possible this may end up to be the first of many similar files for alternate IDEs, so accepting it will influence whether to accept and maintain any others that are submitted.

**Comment by ivankravets** [comment]
1. I don't know what does mean `library.properties`. This like a car without engine, wheels and windows. `library.json` was presented to community 2 years ago. I contacted to Arduino CC and proposed them to use PlatformIO Library Registry. In that time, Arduino IDE hasn't had "Library Manager" yet... See the big dicussion https://groups.google.com/a/arduino.cc/forum/?fromgroups#!searchin/developers/platformio/developers/xCDjekcQW4k/LgkhctVLyGcJ
2. As a result, they decided to invent own "bicycle" that can't allow describing library, dependencies, extra build options/flags, test options and etc. I don't see future in this format. It is useful only for Arduino IDE.
3. " and nothing in the file itself indicates that it's for PlatformIO". The answer is simple - we propose embedded community really independent library manifest file that can be used with other library managers, IDEs and etc. 
4. PlatformIO isn't only IDE. This is a big ecosystem for embedded development. We support other development platforms, frameworks, boards... What is more, it can be integrated into popular IDEs (Eclipse, Microsoft Visual Studio, Emacs, CLion and etc). 
5. You can close this PR without merging. The `library.json` will be located in @valeros fork.

Have a nice day!

**Comment by shogerr** [comment]
It seems in the modern development world, the project root directory is home to all sorts of files, like dockerfiles and vagrantfiles, I think this is a good addition - the package file - but we need to go back and edit the 1.1 release if this is going to be useful.

The package file is very useful for future projects, and as the scope of the Arduboy changes with use case, users will start wanting a bit more of a support library, and node is positioned to offer this.

**Comment by shogerr** [comment]
@valeros, could you switch it back to 1.2.0-alpha for the master branch, and then we will work on a push to 1.1. I use npm quite a bit, and dig integrating this functionality a great deal.

The tag for 1.1 needs to be redone so that the library manager picks it up.

**Comment by ivankravets** [comment]
> could you switch it back to 1.2.0-alpha for the master branch

Could you make `1.2.0-alpha` tag? https://github.com/Arduboy/Arduboy/releases

**Comment by shogerr** [comment]
If you create the alpha tag, it will push the library to the arduino lib manager (i'm 99% sure), if that's something @MLXXXp can get behind, I am ok with. It might solve some of the problems with the mismatching APIS, but we really don't like the print class being separate right now, and that is sort of holding us up into someone reworks it. Probably just do it through inheritance. Anyway, when that is done, the 1.1 and 1.2 api will line up, as print will still be a member function of the Arduboy class.

**Comment by MLXXXp** [comment]
I would add it to the _stable_ branch and release it as V1.1.1

I'd still recommend adding a _library.json.md_ file that describes why _library.json_ is there, what it's used for, and indicating that the version number in it has to be kept in sync with the latest library release version.

**Comment by MLXXXp** [comment]
> I would add it to the stable branch

If <strike>ParticleIO</strike> PlatformIO needs to pick it up from the _master_ branch, it could also be added there. Just set the _version:_ value in it to _1.1.1_

**Comment by ivankravets** [comment]
> I'd still recommend adding a library.json.md file that describes why library.json is there, what it's used for, and indicating that the version number in it has to be kept in sync with the latest library release version.

I don't have any objections.

> If ParticleIO needs to pick it up from the master branch,

Do you mean PlatformIO? If yes, you have a lot of options:
1. `branch` property for repository http://docs.platformio.org/en/latest/librarymanager/config.html#repository
2. Different cases with `version` field http://docs.platformio.org/en/latest/librarymanager/config.html#version

We don't update your library in PlatformIO Registry while you will not change the version in manifest. 

> If you create the alpha tag, it will push the library to the arduino lib manager (i'm 99% sure),

Sorry, I'm not interested in that `library.properties` and don't know what they (Arduino IDE devs) do with this file.

---

If this a problem with Arduino IDE, we can create temporary separate branch and switch users to that. `library.json` allows to do it.

**Comment by MLXXXp** [comment]
> Do you mean PlatformIO?

Yes, sorry, I meant PlatformIO not ParticleIO :blush:

**Comment by MLXXXp** [comment]
Maybe we should just merge this PR as is. This will put the _library.json_ file on the _master_ branch but its _version_ field will indicate that git tag _v1.1_ will be used.

We should then add a _library.json.md_ file as I recommended above.

If we ever have a newer stable release, we'll update the _version_ field in _library.json_, tag/release the library with this new version, and make it the _stable_ branch. After this, newer development can continue on the _master_ branch but we won't change _library.json_ until a new stable version is ready for release.

We'll make it clear in _library.json.md_ that the _version_ field in _library.json_ shouldn't be changed until just before we make a new stable release.

Does this sound OK?

**Comment by shogerr** [comment]
I think we need to keep markdown files out of root and address these issues in the README file. I would totally love to get rid of that upgrading_12 file and put it in the readme file. People see the readme, should really put a note at the top about which repo to use.

So merge, for sure, but please, no more markdown files : )

**Comment by shogerr** [comment]
Here's another thought, maybe we go ahead and create a `docs/` folder now, and place these markdown files in there?

**Comment by MLXXXp** [comment]
Creating a _docs_ folder under the root sort of goes against the Arduino library specification. Making an _extras/docs_ folder would be OK. README.md could then refer to files in _extras/docs_ for anything that wasn't wanted in README.md itself.

**Comment by MLXXXp** [comment]
Maybe instead of a specific _library.json.md_ file we should have a document which describes all files that aren't described in the Arduino library specification, that aren't self documenting (via contained comments, etc.) or don't have an obvious purpose.

We should also have another document describing everything that has to be changed (sort of a checklist) to release a new version, such as:
- Update the version number in the _library.properties_ file
- Update the version number in the _library.json_ file
- Update the version number in the _#define ARDUBOY_LIB_VER_ in _Arduboy.h_
- Make sure _keywords.txt_ has been updated with any new functions or changes
- Make sure the included example sketches still compile and work properly
- Make sure _README.md_ and other documentation is up to date
- Tag the release
- Make the head of the _stable_ branch match the release.
- (whatever else)

**Comment by ivankravets** [comment]
We have updated manifest version to `1.1.1` https://raw.githubusercontent.com/valeros/Arduboy/patch-1/library.json

It means, that PlatformIO Library Crawler will look for `v1.1.1` or `1.1.1` tags. It it will not found these tags, it will use that latest "commit" of the current `default` branch as "tagged" version for `1.1.1`.

**Comment by shogerr** [comment]
If we are ready to merge @MLXXXp feel free : )

**Comment by MLXXXp** [comment]
If we merge it the way it is, with the version set to 1.1.1, then we'll have to create a V1.1.1 release. I'm not sure how we would do that. The _master_ branch is at V1.2 and not ready for release, so we'd have to update and release the _stable_ branch or some other new branch.

Why not just change the version in library.json back to 1.1 and then merge it into _master_. Wouldn't that work?

**Comment by ivankravets** [comment]
@MLXXXp As I said above, we can use the different options from `library.json` manifest. The another option is to directly specify path to the source files with own version. For example,

``` json
{
    "name": "Arduboy",
    "keywords": "arduboy, game",
    "description": "This library is for content creation on the Arduboy, a portable gaming platform.",
    "repository":
    {
        "type": "git",
        "url": "https://github.com/Arduboy/Arduboy.git",
        "branch": "stable"
    },
    "version": "1.1.0",
    "exclude": "extras",
    "frameworks": "arduino",
    "platforms": "atmelavr"
}
```

This file could be merged directly to master branch where PlatformIO will use the all data from manifest and use `stable` source files.

**Comment by MLXXXp** [comment]
With the example above, what happens if the head of the _stable_ branch doesn't match tagged version 1.1.0? Which takes precedence?

Wouldn't it be better just to leave out the `"branch": "stable"` field and set `"version": "1.1"` and merge library.json into _master_? Would PlatformIO then pick up library.json from _master_ but use the source from tag v1.1?

**Comment by ivankravets** [comment]
> With the example above, what happens if the head of the stable branch doesn't match tagged version 1.1.0? Which takes precedence?

It will use the latest commit from `stable` branch

> Wouldn't it be better just to leave out the "branch": "stable" field and set "version": "1.1" and merge library.json into master? Would PlatformIO then pick up library.json from master but use the source from tag v1.0?

If you need to use `tagged` version, the branch doesn't matter here. Here is the final config:

``` json
{
    "name": "Arduboy",
    "keywords": "arduboy, game",
    "description": "This library is for content creation on the Arduboy, a portable gaming platform.",
    "repository":
    {
        "type": "git",
        "url": "https://github.com/Arduboy/Arduboy.git"
    },
    "version": "1.1",
    "exclude": "extras",
    "frameworks": "arduino",
    "platforms": "atmelavr"
}
```

**Comment by MLXXXp** [comment]
> Here is the final config:

Which I believe is identical (except for swapped _extras_ and _version_ fields) to the [_Switch to stable version_](https://github.com/Arduboy/Arduboy/pull/137/commits/3819c5f6d109b26b5241ca569bfee149909eb2f3) commit of this PR (made previous to the latest commit).

So if the PR could be rebased/squashed or otherwise submitted as just that commit, to keep things clean, I think it could be merged to _master_ and we'd be done.

**Comment by ivankravets** [comment]
@valeros Please close this PR and remove `path-1` and open new PR with the config above https://github.com/Arduboy/Arduboy/pull/137#issuecomment-225184395

Thanks.

**Comment by MLXXXp** [comment]
This PR was resubmitted and merged as PR #140

**Pull request closed without merging**
