### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MLXXXp**
This is what I feel is acceptable for a 1.1.1 release of the Library.

### CODE REVIEW

**Comment by shogerr** [comment]
Ah, hey, I had a push from last night I put in just now, I'll look and see if this should be merged on top. Thanks @MLXXXp

**Comment by shogerr** [comment]
Also, I put the library.json file in assets for now. PlatformIO users can symbolically link this for now on the stable branch. My main complaint here is the lack of the ability to comment the file (it's a parsed json file of course), so there is no way to tell users what this file is for, and seems out of place in the root at this point.

**Comment by MLXXXp** [comment]
Regarding README.md

I don't think there should be a different version in every branch, with one saying _"This is the **stable** branch..."_ and another saying _"This is the **develop** branch..."_, etc.

The _develop_ branch should contain exactly what you intend to merge into the _stable_ branch. Currently, if you were to merge _develop_ into _stable_, README.md would now say _"This is the **develop** branch..."_ and you would then have to do another commit to change it back to _stable_. It's likely that someone will forget to make this change somewhere along the line, causing confusion. Likewise, if you branch from _stable_ to create a different development branch, you again have to change README.md, and again have to remember to change it back after merging to _stable_.

Also, having a README.md that says _"This is the **stable** branch..."_ for a library that has been installed using the Arduino Library Manager has no meaning for someone reading it there, now that it's outside of a Git repository. Ultimately, I think that's how README.md should be targeted. And we should also consider what README.md should say in the _master_ branch on GitHub, which is the first thing someone will read when they go there. (And again I'll ask: What is the _master_ branch supposed to be used for?)

The [README.md](https://github.com/MLXXXp/Arduboy/blob/a95f146c34e7d6e0604666c94d7192528e963bd3/README.md) that I made this PR for tries to address this.

**Comment by MLXXXp** [comment]
> Also, I put the library.json file in assets for now.

I was under the impression that we wanted to make it easy for PlatformIO. That means having _library.json_ in the root. I originally [suggested that _library.json_ not be in the root](https://github.com/Arduboy/Arduboy/pull/137#issuecomment-222708151) but [you](https://github.com/Arduboy/Arduboy/pull/137#issuecomment-223706131) and others convinced me otherwise.

I created [extras/docs/FILE_DESCRIPTIONS.md](https://github.com/Arduboy/Arduboy/blob/develop/extras/docs/FILE_DESCRIPTIONS.md) to address the problem of documenting what the purpose is of files that can't self-describe themselves. I suggest we move _library.json_ back to the root and merge in _FILE_DESCRIPTIONS.md_ from the _develop_ branch. (I had intended to make a PR that added _FILE_DESCRIPTIONS.md_ to _stable_, and can still do so, if you wish.)

**Comment by MLXXXp** [comment]
Another thing I think we should add is a description of what has been added, changed and fixed for each release (a "change log"). We could probably just put this at the end of README.md

**Comment by shogerr** [comment]
For files in the root, as an aid to users, we might specify that a comment be placed at the top of files. We can't do this with json files, but we can look at adding a comment key to the block itself. For the stable branch, we can keep things tight, and extraneous files out of root, for master and develop we can add those files into the root for developers.

Changelogs are being tracked with the release system, but we should look around for good examples of how to put on in the root or extras/docs. Usually the README.md is used to provide a description of each of the files, sometimes in a ToC at the beginning of the README

**Comment by shogerr** [comment]
Also, adjusting the readme on the stable branch to not reflect it as a branch from a git repository, but as an Arduino library, is a way better idea; especially if the branch is dedicated to the arduino release system. Maybe just a mention of, "the source for this library can be found at...", or something to that effect.

**Comment by MLXXXp** [comment]
> For the stable branch, we can keep things tight, and extraneous files out of root, for master and develop we can add those files into the root for developers.

No you can't, for a reason similar to why we shouldn't have different versions of README.md in each branch. Once you merge, someone has to remember to remove the extraneous files, which likely someone will forget to do.

You should be able to quickly merge a development branch to _stable_ and then just tag it as a release, without any further commits. At that point, the contents of _stable_ should be identical to _development_. You then continue adding new commits to _develop_ until you're again ready to merge to _stable_ and release/tag again.

**Comment by MLXXXp** [comment]
I'm asking again... What is the _master_ branch intended to be used for???

**Comment by shogerr** [comment]
As much as i'm tempted to remove the `master` branch and set the default to `stable`, we will probably end up doing branches like `1-2-stable`, `1-3-stable`, `...`, `2-1-stable`, `...`, `m-n-stable`, where `m` and `n` are major and minor versions, respectively; also, with this model  stable isn't limited to just one branch, and releases are archived as we go by branch - not by commit tag, a convenience for all users. 

The `master` will be the default repository that is set to the last `m-n-stable` branch the library was built from. By doing this we allow files to be put in root for developers targeting the latest stable release (like `library.json`), we also have a place to test patches on targeting the latest release, and we can provide documentation targeted at Github users when they load the page, not our Arduino library users as we do in `stable`. 

And of course, the `develop` and `<user>/develop` branches are where developers are free to express and aggressively push change, and where our `m-n-<development tag>` branches can be forked from before they are migrated to a `m-n-stable` for release. 

Checkout the Rails repository for a decent example of this in practice.
https://github.com/rails/rails

**Comment by shogerr** [comment]
> No you can't, for a reason similar to why we shouldn't have different versions of README.md in each branch.

You _should_ have different readme files for each branch, as each branch may be installed and perform differently, or have notes specific to that branch. Check out some of the big Github projects out there and see what you think.

**Comment by MLXXXp** [comment]
> as much as i'm tempted to remove the master branch and set the default to stable, we will probably end up doing branches like `1-2-stable`, `1-3-stable`, ..., `2-1-stable`, ..., `m-n-stable`

Why? That's what [releases/tags](https://github.com/Arduboy/Arduboy/releases) are for. Why are you trying to come up with a new technique for a something that Git already provides one for?

Branches are mainly intended for temporary new development and testing without disturbing the one stable release branch (which could be _master_, or _master_ could be for development). Once the changes are merged to create a new stable release, the branch can be discarded or used for continued new development. The only other reason would be to maintain versions for separate products, but you'd be better to use separate repositories for that.

I'd like to see you find another Git repository that keeps each stable release on a separate branch. There's no need.

**Comment by shogerr** [comment]
> I'd like to see you find another Git repository that keeps each stable release on a separate branch. There's no need.

One was provided in the comment you are responding to.

**Comment by MLXXXp** [comment]
> You should have different readme files for each branch, as each branch may be installed and perform differently, or have notes specific to that branch.

Only if the branches are maintained for separate products, not for a new successor library version for the same product.

**Comment by shogerr** [comment]
Eh, as a github user, if I'm a development branch, I'd like a little note in the README for that software package telling me where in the world I am in space and time. I see what you are saying about a README file like you expect when you open a zip distributed by a group, it's static with a changelog pasted in... so I sort of see... I'd still expect detailed notes to be present about the current version perhaps if it was a development build, maybe in another file though.

Github is changing that a bit, and how users get on and view and use code. We could try a single README.md, doesn't hurt to try and write one. For this release, I'd rather not get stuck on this aspect, and let's say we just double check the current release and shoot for a commit tag to be made tonight? Ye, nay?

**Comment by MLXXXp** [comment]
> Checkout the Rails repository for a decent example of this in practice.

With Rails, you can have different versions installed at the same time, essentially different products. With the Arduboy library, only one version (presumably the latest) can be installed.

Can you give me a good reason why Rails does this? What does it accomplish?

**Comment by shogerr** [comment]
> Can you give me a good reason why Rails does this? What does it accomplish?

See [this](https://github.com/Arduboy/Arduboy/pull/150#issuecomment-237977230) comment, but the second paragraph.

**Comment by MLXXXp** [comment]
>  For this release, I'd rather not get stuck on this aspect, and let's say we just double check the current release and shoot for a commit tag to be made tonight? Ye, nay?

Agreed. Let's get something out there. Hopefully something from the _develop_ branch will replace it shortly, anyway (hint, hint :wink: )

I've tested and checked the fix as well as I can. Unless you want to do more testing, or check other aspects of the release, I'd say we're good to go.

**Comment by shogerr** [comment]
As a collaborator, I believe it's possible for you to tag the release and add it to our releases. Would you like to tag and push the release? I only provide the release notes for 1.1 as a model, feel free to come up with something that works or looks better. 

If you aren't able to tag it, or would prefer I do it, let me know. I'm ok with everything, I would have loved to beef up the doxy stuff, but pfft, as you say lets get the develop branch into the stable for the next release, and that will take care of the doxy markup.

**Comment by MLXXXp** [comment]
> As a collaborator, I believe it's possible for you to tag the release and add it to our releases. Would you like to tag and push the release?

I've already previously offered to do this. Do you want to do any more checking before I do or can I proceed as soon as I'm able?

**Comment by MLXXXp** [comment]
Note that when after I've tagged the release, I'll also update the version in _library.json_ in the **master** branch so that ParticleIO will pick it up.

**Comment by shogerr** [comment]
Haha, well, we push it out the door only with green lights all around, so yeah green light, push it as soon as you are able. 

And sounds good about shifting the json file around. I am thinking we merge from stable to master, then tag the release from master? After which the json file is added and commited? And we can pause and rethink if we need a readme.md change at all, maybe make some rough drafts.

So yeah go for it! I look forward to the next release ^_^

**Comment by MLXXXp** [comment]
> And sounds good about shifting the json file around. I am thinking we merge from stable to master, then tag the release from master? 

There's no need to merge or tag to _master_. I'll tag the release in _stable_. Just updating the _library.json_ in _master_ is sufficient to have ParticleIO automatically pick up the new release. (It looks in _master_ for _library.json_ and then uses the version it finds in it for the tagged version to retrieve.)

**Comment by shogerr** [comment]
please tag from master, thanks. If you need a reason, it's in the event stable is ever removed.

**Comment by MLXXXp** [comment]
> please tag from master

I have a feeling I won't be able to merge _stable_ to _master_ in a hurry due to conflicts. There's been too many new commits since _stable_ was branched off.

I don't think _stable_ can be removed, anyway. If you look at the [branches](https://github.com/Arduboy/Arduboy/branches), you'll see that there's a lock icon beside _stable_ and the "trash can" for deleting it has been greyed out. I think this indicates that it has been previously tagged or has been referenced in some other way such that it can't be removed.

Besides, a Git "golden rule" is that you should never rewrite history in a public repository. Someone may already have pulled a local repository from this branch and you'd screw them up if they wanted to submit changes based on it.

**Comment by Pharap** [comment]
I apologise for having only skimmed this conversation as it seems to span several hours of discusssion. Ironically I agree with most the points made by both of you and while it seems you've agreed to put off the conversation regarding the best approach to the way the library should be structured in terms of git, I think this is definately an important conversation to have.

I'm not entirely sure this is the place to have it (i.e. tacked on to a PR), but I think it's a good thing to discuss. I won't go too in depth about it now (since you've rather amicably agreed to postpone the discussion) but I will offer a few of my thoughts on the matter.

I agree that it's not good to be having to overwrite the readme after every merge from develop to stable.
The readme should be somewhat universal in describing the purposes of the different branches and providing additional information such as links to 'official' tutorials, and how to perform commonly needed information such as _basic_ installation and how to acquire different versions of the library.

I also agree that in some circumstances it might be good to know which version you're working with. Frankly though, unless you've installed the wrong version by accident, that should be a bit of a non issue as you have to go out of your way to download development instead of stable. To this end, I believe the solution would be to add something to the develop branch whilst it is in development to signify it a development branch (for example a 'develop.txt' file or something) and then remove this before finalising as stable.

I can't comment on the tags system before looking into it, so I don't have an official opinion on whether the `major-minor-stable`/`major-minor-develop` system is better than tags, but I will say the tags system is less obvious unless explicitly mentioned in the readme. I think on this particular issue more people would have to be consulted, and maybe a vote taken (probably the group of most active developers... which I'm hoping is more than just 2 people now that I've said that).

The other matters I won't discuss because I don't have enough knowledge about them to have any opinon. I will say however, that pretty much everything discussed here is mostly a behind the scenes matter and can stay up in the air for now without harming the next release.

**Comment by MLXXXp** [comment]
> To this end, I believe the solution would be to add something to the develop branch whilst it is in development to signify it a development branch (for example a 'develop.txt' file or something) and then remove this before finalising as stable.

As long as no one ever forgets to remove it before merging to and tagging _stable_.

I've been thinking it would be a good idea to put a document in _extras_, something like _RELEASING.md_, with instructions and a check list of what to do before releasing a stable version.
It would contain things like:
- Update the version number &lt;here&gt;, &lt;here&gt; and &lt;here&gt;
- If any public functions were added, deprecated or removed, update _keywords.txt_ to match.
- Delete file _develop.txt_
- Update the change log.

**Comment by shogerr** [comment]
Closing this, please open an issue related to a topic of this PR to continue the discussion of a topic found in this PR.

**Pull request closed without merging**
