### PR TITLE
compile flags to support production hardware, plus RGB led support

### PR DESCRIPTION
**Pull request by joshgoebel**
Would like at least one other person with production hardware to test this before we merge.

### CODE REVIEW

**Comment by yyyc514** [comment]
Don't merge will I figure out why my editor is putting ^M everywhere.

**Comment by shogerr** [comment]
It means you have a windows newline char with both a carriage return and a new line and its being displayed in linux. This project should use unix new lines, so just 0x0a

In vim: :%s/^V^M//g to replace

**Comment by joshgoebel** [comment]
example

**Comment by joshgoebel** [comment]
Ready for review.

**Comment by shogerr** [comment]
Everything looks fine to me, nice commenting as well. I will leave this un-merged for a few more hours for review before merging.

**Comment by joshgoebel** [comment]
Awesome!

**Pull request merged**
