### PR TITLE
Fixed an issue where the ArduBreakout.ino example

### PR DESCRIPTION
**Pull request by tzikis**
There was an unprintable characted in 3 lines, which broke compilation (at least on Unix systems)

### CODE REVIEW

**Comment by shogerr** [comment]
Thanks, I'm thinking someone put a carriage return \r or something in there because it's sort of a long line.

**Comment by shogerr** [comment]
Don't be davidperrnoud. We really need an automated build system in for both windows and linux that does a build status.

**Comment by tzikis** [comment]
sorry guys, looks like i forgot to fix one of the errors, i think there's still one on line 311 (same place as in the other lines)

@rogosher well once the library is up on codebender, we take care of all that, that's actually how we found out about this issue :)

**Comment by shogerr** [comment]
The main repository still needs a method to check PRs from users. Not sure what the solution is there, probably travis-ci or something. One of these days.

**Comment by tzikis** [comment]
time for my shameless plug here :) we (codebender) doesn't have anything like that, but what you said yesterday actually got me thinking of building such a service exactly, and how we can leverage our existing infrastructure to build something like that

if you pay for that, we'll build it :)

also, please do fix the issue on line 311, i don't think it's big enough for me to make a separate PR :)

**Comment by shogerr** [comment]
Removed the offending character. I am hoping checking in the unix like environment will be as simple as an automated makefile being ran. That's my hope anyway, or something like that. Not sure about windows atm.

**Comment by tzikis** [comment]
great! now the problem should be solved!

well, the problem is a bit more complex, especially since the arduino ide doesn't make it too easy to call it in a makefile, and then there are things like different board configs (not applicable to arduboy but still valid), and potential dependencies with libraries (and most usually, specific versions of libraries)

then there is the issue of different arduino ide version. not all people convert to the latest as soon as it comes up. most people are still using 1.0.x, and I remember the Sprinter firmware was compatible with the horrible Arduino 0.22 for 2 years after 1.0.0 was released

**Pull request merged**
